services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - MYSQL_ROOT_PASSWORD=you_cant_crack_this
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: you_cant_crack_this
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
